# Generated by Django 3.1.3 on 2020-11-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
